const fs = require('node:fs');
const path = require('node:path');
const dotenv = require('dotenv');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outputPath = path.join(rootDir, 'public', 'js', 'env.js');

const result = dotenv.config({ path: envPath });
if (result.error) {
  console.warn('[generate-env] .env file was not found or could not be read. Generating empty config.');
}

const allowedKeys = [
  'GOOGLE_API_KEY',
  'GOOGLE_CALENDAR_ID'
];

const browserEnv = {};
for (const key of allowedKeys) {
  browserEnv[key] = process.env[key] || '';
}

const fileContent = `// Auto-generated by scripts/generate-env.js\n// Do not edit manually. Update .env and rerun npm run env:generate\nexport const ENV = ${JSON.stringify(browserEnv, null, 2)};\n`;

fs.writeFileSync(outputPath, fileContent, 'utf8');
console.log(`[generate-env] Wrote ${outputPath}`);
